[versions]
springBoot = "3.3.5"
springDependencyManagement = "1.1.7"
kotlin = "2.2.0"
coroutines = "1.7.2"
jjwt = "0.12.5"
aws = "2.34.0"

[libraries]
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-data-r2dbc = { module = "org.springframework.data:spring-data-r2dbc" }
r2dbc-pool = { module = "io.r2dbc:r2dbc-pool" }
r2dbc-postgresql = { module = "org.postgresql:r2dbc-postgresql" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
springdoc-openapi-webflux-ui = { module = "org.springdoc:springdoc-openapi-starter-webflux-ui", version = "2.6.0" }
webjars-locator-core = { module = "org.webjars:webjars-locator-core" }

# AWS
aws-s3-core = { module = "software.amazon.awssdk:s3", version.ref = "aws"}

# build-logic
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin"}

takealook-spring-application-convention = { id = "takealook.spring.application.convention" }
takealook-spring-library-convention = { id = "takealook.spring.library.convention" }
takealook-kotlin-module-convention = { id = "takealook.kotlin.module.convention" }
takealook-feature-module-convention = { id = "takealook.feature.module.convention" }
takealook-spring-swagger-convention = { id = "takealook.spring.swagger.convention" }